### ISSUE TITLE
Superpose Problem after loaded trajectory with dask-traj

### ISSUE THREAD

**Issue by Bio-Otto** [sroet/dask-traj#10]
How can I superpose trajectory after loaded it with dask-traj? Actually, I did. But it is used too high an amount of ram and then an error occurring.

**Comment by sroet** [comment]
Do you mind sharing the code that you are trying to run, together with the final error?

This project is still in development, and functions that are not implemented (yet),
Hence the following text on the main code page:
> If a function of MDTraj that you want to use is not yet supported here, please raise an issue. That way we know where to focus our efforts on.

However, to make make some of the missing features less severe, we attempt to default to regular `MDTraj` functions, (such as for `superpose`). 
This has as side effect that all the data has to be loaded into memory, which can lead to issues if the trajectory does not fit into memory. Is this the effect that you are seeing or is it using significant more memory than you would expect from pure `mdtraj`?

**Comment by Bio-Otto** [comment]
Normally, superpose operation can be applied separately for each chunk with mdtraj. But here, when I try it with a 25000 frame XTC file, the ram usage goes up to 16 GB and gives some errors. Maybe this error is due to insufficient ram capacity. If so, it needs to be fixed. I enclosed a simple example here.

``` python
def plot_rmsd(trajectory, topology, chunksize=100):
    import mdtraj
    import dask_traj as dmt

    topology = mdtraj.load_topology(topology)
    first_frame = mdtraj.load_frame(trajectory, 0, top=topology)

    itertraj = dmt.load(trajectory, top=topology, chunks=chunksize)
    itertraj.superpose(reference=first_frame)

plot_rmsd(dcd_file, topology=pdb_file)

```
