### ISSUE TITLE
Add link to docs in README.md

### ISSUE THREAD

**Issue by ocaisa** [sroet/dask-traj#6]
Currently the online version of the docs at https://dask-traj.readthedocs.io/en/latest/ is not linked in the `README.md`, maybe you want to add the docs link to your conda-forge PR too? Not sure if that's considered the right thing to do...

**Comment by sroet** [comment]
Thanks for the tip: does commit https://github.com/sroet/dask-traj/commit/008ad0e6325d1b7a82b9bebb1d39436fff592bed resolve this issue for you?

**Comment by ocaisa** [comment]
Above and beyond :)
